name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - run: npm install

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Proper SSH key setup
      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GO_REALM_DEPLOY_KEY }}

      # Verify the key was added (debugging step)
      - name: List SSH keys
        run: ssh-add -l

      # Improved SSH deployment
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.GO_REALM_DEPLOY_KEY }} # Directly pass the key
          port: 22
          script: |
            cd /var/www/html/go-realm
            git pull
            npm install
            npm run build
            pm2 reload go-realm || pm2 start npm --name "go-realm" -- start -- -p 4300 -H 0.0.0.0
